### ISSUE TITLE
A couple clarifications

### ISSUE THREAD

**Issue by kmatch98** [DDeGonge/TicTacToe-Bot#1]

**Comment by kmatch98** [comment]
First, this is awesome!  End of last year I made a two link robot arm and wanted to make a GCode plotter but I couldn’t stomach to do the math and so I just let it lie dormant. Thanks for doing this!

I have a couple of questions for you:
1.  What does this x and y offset mean?  Maybe a napkin drawing would help?
```
float x0_offset_mm = 25;
 float y0_offset_mm = 135;
```

2.  I see that the homing routine isn’t written, but how do you manage it anyway? Maybe related to above, If my homing position is different would the homing position affect the offsets?

3.  The arc drawing is missing. Do you have a way of generating gcode with only lines?

Thanks a lot for this, and thanks for sharing.

**Comment by DDeGonge** [comment]
Sorry I'm pretty terrible at documenting things, I intend to at least improve the readme by the weekend!

1. These are the distances from the 0,0 position to the point of rotation where the first arm connects to the base. Basically where the scara arm starts.

2. I do have a janky "homing" routine function which simply allows you to move the bot so the pen is near zero, it then enables the motor and lets you fine tune the position before accepting. It isn't great but I didn't add any limit switches to the hardware so this was the best I could do haha.

3. I just use Cura and added custom retraction code for my pen. It seems to not use any arcs in the gcode it produces but your results may vary. You could always take a crack at implementing arc control, I'd be happy to merge it into my code if you are successful :D
